#!/bin/sh
# Simple script for running a maven project from the terminal

if [ -f target/jvmargs ]
then
	EXTRA_JVM_ARGS=`cat target/jvmargs`
else 
	EXTRA_JVM_ARGS="-Xmx512M"
fi

if [ -f target/appargs ]
then
	APP_ARGS=`cat target/appargs`
else 
	APP_ARGS="-webRoot=target/classes/public -development=true"
fi

env MAVEN_OPTS="$EXTRA_JVM_ARGS" mvn --settings neo4j-repo.xml compile exec:java -Dexec.args="$APP_ARGS -development=true" "$@"
